[package]
name = "mpq"
version = "0.1.0"
authors = ["Michael Sierks <msierks117@gmail.com>"]
license = "MIT"
description = "A library for reading MPQ archives"
repository = "https://github.com/msierks/mpq-rust"
readme = "README.md"
keywords = ["mpq", "archive"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[[bin]]
name = "mpq"
doc = false

[dependencies]
byteorder = "0.5"
flate2 = "0.2"
getopts = "0.2"
